package migrations

import (
	"log"
	"strings"

	"github.com/florus/backend/internal/models"
	"gorm.io/gorm"
)

func AutoMigrate(db *gorm.DB) error {
	log.Println("Running auto-migration...")

	// Migrate each model separately to ensure all tables are created
	// even if some models have constraint errors
	modelsToMigrate := []interface{}{
		&models.User{},
		&models.Category{},
		&models.Product{},
		&models.ProductTag{},
		&models.ProductIngredient{},
		&models.ProductRelationship{},
		&models.ProductImage{},
		&models.CartItem{},
		&models.Order{},
		&models.OrderItem{},
		&models.WishlistItem{},
		&models.Review{},
		&models.Coupon{},
	}

	var hasErrors bool
	for _, model := range modelsToMigrate {
		err := db.AutoMigrate(model)
		if err != nil {
			// Ignore Oracle errors for existing objects
			// ORA-00955: name already used by an existing object (index exists)
			// ORA-02261: unique or primary key already exists
			// ORA-01430: column being added already exists
			if strings.Contains(err.Error(), "ORA-00955") ||
				strings.Contains(err.Error(), "ORA-02261") ||
				strings.Contains(err.Error(), "ORA-01430") {
				// Silently continue - object already exists
				continue
			}
			log.Printf("Migration warning for %T: %v", model, err)
			hasErrors = true
		}
	}

	// Create payments table manually due to Oracle constraint issues with related models
	createPaymentsTable(db)

	// Create user_events table manually
	createUserEventsTable(db)

	// Create reviews table manually due to Oracle constraint issues
	createReviewsTable(db)

	if hasErrors {
		log.Println("Migration completed with some warnings")
	} else {
		log.Println("Migration completed successfully")
	}
	return nil
}

func createPaymentsTable(db *gorm.DB) {
	// Check if payments table exists
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'PAYMENTS'").Scan(&count)
	if count > 0 {
		return // Table already exists
	}

	log.Println("Creating payments table...")
	sql := `
		CREATE TABLE payments (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			ORDER_ID INTEGER NOT NULL,
			TRANSACTION_ID VARCHAR2(100),
			METHOD VARCHAR2(20) NOT NULL,
			AMOUNT NUMBER(15,2) NOT NULL,
			STATUS VARCHAR2(20) DEFAULT 'pending',
			PROVIDER_TRANS_ID VARCHAR2(100),
			PAYMENT_URL VARCHAR2(1000),
			CALLBACK_DATA CLOB,
			ERROR_MESSAGE VARCHAR2(500),
			PAID_AT TIMESTAMP WITH TIME ZONE,
			CREATED_AT TIMESTAMP WITH TIME ZONE,
			UPDATED_AT TIMESTAMP WITH TIME ZONE,
			CONSTRAINT FK_PAYMENTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES orders(ID)
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating payments table: %v", err)
		}
	} else {
		log.Println("Payments table created successfully")
	}

	// Create unique index on transaction_id
	db.Exec("CREATE UNIQUE INDEX IDX_PAYMENTS_TRANSACTION_ID ON payments(TRANSACTION_ID)")
	// Create index on order_id
	db.Exec("CREATE INDEX IDX_PAYMENTS_ORDER_ID ON payments(ORDER_ID)")
}

func createUserEventsTable(db *gorm.DB) {
	// Check if user_events table exists
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'USER_EVENTS'").Scan(&count)
	if count > 0 {
		return // Table already exists
	}

	log.Println("Creating user_events table...")
	sql := `
		CREATE TABLE user_events (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			USER_ID INTEGER,
			SESSION_ID VARCHAR2(100),
			EVENT_TYPE VARCHAR2(50) NOT NULL,
			PRODUCT_ID INTEGER,
			CATEGORY_ID INTEGER,
			ORDER_ID INTEGER,
			SEARCH_QUERY VARCHAR2(255),
			QUANTITY INTEGER,
			PRICE NUMBER(15,2),
			RATING INTEGER,
			METADATA CLOB,
			USER_AGENT VARCHAR2(500),
			IP_ADDRESS VARCHAR2(45),
			REFERRER VARCHAR2(500),
			CREATED_AT TIMESTAMP WITH TIME ZONE
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating user_events table: %v", err)
		}
	} else {
		log.Println("User_events table created successfully")
	}

	// Create indexes
	db.Exec("CREATE INDEX IDX_USER_EVENTS_USER_ID ON user_events(USER_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_SESSION_ID ON user_events(SESSION_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_EVENT_TYPE ON user_events(EVENT_TYPE)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_PRODUCT_ID ON user_events(PRODUCT_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_CATEGORY_ID ON user_events(CATEGORY_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_CREATED_AT ON user_events(CREATED_AT)")
}

func createReviewsTable(db *gorm.DB) {
	// Check if reviews table exists
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'REVIEWS'").Scan(&count)
	if count > 0 {
		return // Table already exists
	}

	log.Println("Creating reviews table...")
	sql := `
		CREATE TABLE reviews (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			USER_ID INTEGER NOT NULL,
			PRODUCT_ID INTEGER NOT NULL,
			RATING INTEGER NOT NULL,
			"COMMENT" CLOB,
			CREATED_AT TIMESTAMP WITH TIME ZONE,
			UPDATED_AT TIMESTAMP WITH TIME ZONE,
			CONSTRAINT FK_REVIEWS_USER FOREIGN KEY (USER_ID) REFERENCES users(ID),
			CONSTRAINT FK_REVIEWS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID),
			CONSTRAINT UQ_REVIEWS_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating reviews table: %v", err)
		}
	} else {
		log.Println("Reviews table created successfully")
	}

	// Create indexes
	db.Exec("CREATE INDEX IDX_REVIEWS_USER_ID ON reviews(USER_ID)")
	db.Exec("CREATE INDEX IDX_REVIEWS_PRODUCT_ID ON reviews(PRODUCT_ID)")
}
