package migrations

import (
	"log"
	"strings"

	"github.com/florus/backend/internal/models"
	"gorm.io/gorm"
)

func AutoMigrate(db *gorm.DB) error {
	log.Println("Running auto-migration...")

	// Migrate each model separately to ensure all tables are created
	// even if some models have constraint errors
	modelsToMigrate := []interface{}{
		&models.User{},
		&models.Category{},
		&models.Product{},
		&models.ProductTag{},
		&models.ProductIngredient{},
		&models.ProductRelationship{},
		&models.ProductImage{},
		&models.CartItem{},
		&models.Order{},
		&models.OrderItem{},
		&models.WishlistItem{},
		&models.Review{},
		&models.ReviewImage{},
		&models.Coupon{},
		&models.UserAddress{},
		&models.ShippingZone{},
		&models.ShippingMethod{},
		&models.ShippingZoneMethod{},
		&models.LoyaltyTransaction{},
		&models.Return{},
		&models.ReturnItem{},
	}

	var hasErrors bool
	for _, model := range modelsToMigrate {
		err := db.AutoMigrate(model)
		if err != nil {
			// Ignore Oracle errors for existing objects
			// ORA-00955: name already used by an existing object (index exists)
			// ORA-02261: unique or primary key already exists
			// ORA-01430: column being added already exists
			if strings.Contains(err.Error(), "ORA-00955") ||
				strings.Contains(err.Error(), "ORA-02261") ||
				strings.Contains(err.Error(), "ORA-01430") {
				// Silently continue - object already exists
				continue
			}
			log.Printf("Migration warning for %T: %v", model, err)
			hasErrors = true
		}
	}

	// Create core business tables that may fail with GORM+Oracle automigration
	// Products table is critical for most user flows, so ensure it's present.
	createProductsTable(db)
	createProductTagsTable(db)
	createProductIngredientsTable(db)
	createProductRelationshipsTable(db)
	createProductImagesTable(db)
	createCartItemsTable(db)
	createWishlistItemsTable(db)

	// Ensure orders core tables exist before payments (which has FK to orders)
	createOrdersTable(db)
	createOrderItemsTable(db)
	ensureOrderExtraColumns(db)

	// Create payments table manually due to Oracle constraint issues with related models
	createPaymentsTable(db)

	// Create user_events table manually
	createUserEventsTable(db)

	// Ensure loyalty-related columns exist on users
	ensureUserLoyaltyColumns(db)

	// Create reviews table manually due to Oracle constraint issues
	createReviewsTable(db)
	createReviewImagesTable(db)

	if hasErrors {
		log.Println("Migration completed with some warnings")
	} else {
		log.Println("Migration completed successfully")
	}
	return nil
}

func createPaymentsTable(db *gorm.DB) {
	// Check if payments table exists
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'PAYMENTS'").Scan(&count)
	if count > 0 {
		return // Table already exists
	}

	log.Println("Creating payments table...")
	sql := `
		CREATE TABLE payments (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			ORDER_ID INTEGER NOT NULL,
			TRANSACTION_ID VARCHAR2(100),
			METHOD VARCHAR2(20) NOT NULL,
			AMOUNT NUMBER(15,2) NOT NULL,
			STATUS VARCHAR2(20) DEFAULT 'pending',
			PROVIDER_TRANS_ID VARCHAR2(100),
			PAYMENT_URL VARCHAR2(1000),
			CALLBACK_DATA CLOB,
			ERROR_MESSAGE VARCHAR2(500),
			PAID_AT TIMESTAMP WITH TIME ZONE,
			CREATED_AT TIMESTAMP WITH TIME ZONE,
			UPDATED_AT TIMESTAMP WITH TIME ZONE,
			CONSTRAINT FK_PAYMENTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES orders(ID)
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating payments table: %v", err)
		}
	} else {
		log.Println("Payments table created successfully")
	}

	// Create unique index on transaction_id
	db.Exec("CREATE UNIQUE INDEX IDX_PAYMENTS_TRANSACTION_ID ON payments(TRANSACTION_ID)")
	// Create index on order_id
	db.Exec("CREATE INDEX IDX_PAYMENTS_ORDER_ID ON payments(ORDER_ID)")
}

func createUserEventsTable(db *gorm.DB) {
	// Check if user_events table exists
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'USER_EVENTS'").Scan(&count)
	if count > 0 {
		return // Table already exists
	}

	log.Println("Creating user_events table...")
	sql := `
		CREATE TABLE user_events (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			USER_ID INTEGER,
			SESSION_ID VARCHAR2(100),
			EVENT_TYPE VARCHAR2(50) NOT NULL,
			PRODUCT_ID INTEGER,
			CATEGORY_ID INTEGER,
			ORDER_ID INTEGER,
			SEARCH_QUERY VARCHAR2(255),
			QUANTITY INTEGER,
			PRICE NUMBER(15,2),
			RATING INTEGER,
			METADATA CLOB,
			USER_AGENT VARCHAR2(500),
			IP_ADDRESS VARCHAR2(45),
			REFERRER VARCHAR2(500),
			CREATED_AT TIMESTAMP WITH TIME ZONE
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating user_events table: %v", err)
		}
	} else {
		log.Println("User_events table created successfully")
	}

	// Create indexes
	db.Exec("CREATE INDEX IDX_USER_EVENTS_USER_ID ON user_events(USER_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_SESSION_ID ON user_events(SESSION_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_EVENT_TYPE ON user_events(EVENT_TYPE)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_PRODUCT_ID ON user_events(PRODUCT_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_CATEGORY_ID ON user_events(CATEGORY_ID)")
	db.Exec("CREATE INDEX IDX_USER_EVENTS_CREATED_AT ON user_events(CREATED_AT)")
}

func createReviewsTable(db *gorm.DB) {
	// Check if reviews table exists
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'REVIEWS'").Scan(&count)
	if count == 0 {
		log.Println("Creating reviews table...")
		sql := `
			CREATE TABLE reviews (
				ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				USER_ID INTEGER NOT NULL,
				PRODUCT_ID INTEGER NOT NULL,
				RATING INTEGER NOT NULL,
				COMMENT_TEXT CLOB,
				CREATED_AT TIMESTAMP WITH TIME ZONE,
				UPDATED_AT TIMESTAMP WITH TIME ZONE,
				CONSTRAINT FK_REVIEWS_USER FOREIGN KEY (USER_ID) REFERENCES users(ID),
				CONSTRAINT FK_REVIEWS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID),
				CONSTRAINT UQ_REVIEWS_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
			)
		`
		if err := db.Exec(sql).Error; err != nil {
			if !strings.Contains(err.Error(), "ORA-00955") {
				log.Printf("Error creating reviews table: %v", err)
			}
		} else {
			log.Println("Reviews table created successfully")
		}
	} else {
		// Table exists: ensure COMMENT_TEXT column exists (older schema may have different layout)
		var colCount int64
		db.Raw("SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'REVIEWS' AND COLUMN_NAME = 'COMMENT_TEXT'").Scan(&colCount)
		if colCount == 0 {
			log.Println("Adding COMMENT_TEXT column to reviews table...")
			if err := db.Exec("ALTER TABLE reviews ADD COMMENT_TEXT CLOB").Error; err != nil && !strings.Contains(err.Error(), "ORA-01430") {
				log.Printf("Error adding COMMENT_TEXT column: %v", err)
			}
		}
	}

	// Create indexes
	db.Exec("CREATE INDEX IDX_REVIEWS_USER_ID ON reviews(USER_ID)")
	db.Exec("CREATE INDEX IDX_REVIEWS_PRODUCT_ID ON reviews(PRODUCT_ID)")
}

// createProductsTable ensures the main products table exists in Oracle.
// In some Oracle setups, GORM's AutoMigrate can fail to create this table
// due to type/constraint translation issues, leading to ORA-00942 when querying.
func createProductsTable(db *gorm.DB) {
	// Check if products table exists
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCTS'").Scan(&count)
	if count > 0 {
		return // Table already exists
	}

	log.Println("Creating products table...")
	sql := `
		CREATE TABLE products (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			NAME VARCHAR2(255) NOT NULL,
			SLUG VARCHAR2(255) NOT NULL,
			BRAND VARCHAR2(100),
			PRICE NUMBER(15,2) NOT NULL,
			ORIGINAL_PRICE NUMBER(15,2),
			CATEGORY_ID INTEGER NOT NULL,
			DESCRIPTION CLOB,
			IMAGE_URL VARCHAR2(500),
			STOCK INTEGER DEFAULT 0,
			RATING NUMBER(3,2) DEFAULT 0,
			REVIEW_COUNT INTEGER DEFAULT 0,
			AI_SCORE NUMBER(5,2),
			AI_RECOMMEND_TYPE VARCHAR2(50),
			IS_ACTIVE NUMBER(1) DEFAULT 1,
			CREATED_AT TIMESTAMP WITH TIME ZONE,
			UPDATED_AT TIMESTAMP WITH TIME ZONE
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating products table: %v", err)
		}
	} else {
		log.Println("Products table created successfully")
	}

	// Indexes and constraints
	db.Exec("CREATE UNIQUE INDEX IDX_PRODUCTS_SLUG ON products(SLUG)")
	db.Exec("CREATE INDEX IDX_PRODUCTS_CATEGORY_ID ON products(CATEGORY_ID)")
	db.Exec("CREATE INDEX IDX_PRODUCTS_IS_ACTIVE ON products(IS_ACTIVE)")
}

func createProductTagsTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCT_TAGS'").Scan(&count)
	if count > 0 {
		return
	}
	log.Println("Creating product_tags table...")
	sql := `
		CREATE TABLE product_tags (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			PRODUCT_ID INTEGER NOT NULL,
			TAG_NAME VARCHAR2(100) NOT NULL
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating product_tags table: %v", err)
		}
	} else {
		log.Println("product_tags table created successfully")
	}
	db.Exec("CREATE INDEX IDX_PRODUCT_TAGS_PRODUCT_ID ON product_tags(PRODUCT_ID)")
}

func createProductIngredientsTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCT_INGREDIENTS'").Scan(&count)
	if count > 0 {
		return
	}
	log.Println("Creating product_ingredients table...")
	sql := `
		CREATE TABLE product_ingredients (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			PRODUCT_ID INTEGER NOT NULL,
			INGREDIENT_NAME VARCHAR2(255) NOT NULL
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating product_ingredients table: %v", err)
		}
	} else {
		log.Println("product_ingredients table created successfully")
	}
	db.Exec("CREATE INDEX IDX_PRODUCT_INGREDIENTS_PRODUCT_ID ON product_ingredients(PRODUCT_ID)")
}

func createProductRelationshipsTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCT_RELATIONSHIPS'").Scan(&count)
	if count > 0 {
		return
	}
	log.Println("Creating product_relationships table...")
	sql := `
		CREATE TABLE product_relationships (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			SOURCE_PRODUCT_ID INTEGER NOT NULL,
			TARGET_PRODUCT_ID INTEGER NOT NULL,
			RELATIONSHIP_TYPE VARCHAR2(50) NOT NULL,
			SCORE NUMBER(5,2)
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating product_relationships table: %v", err)
		}
	} else {
		log.Println("product_relationships table created successfully")
	}
	db.Exec("CREATE INDEX IDX_PRODUCT_REL_SOURCE ON product_relationships(SOURCE_PRODUCT_ID)")
	db.Exec("CREATE INDEX IDX_PRODUCT_REL_TARGET ON product_relationships(TARGET_PRODUCT_ID)")
	db.Exec("CREATE INDEX IDX_PRODUCT_REL_TYPE ON product_relationships(RELATIONSHIP_TYPE)")
}

func createProductImagesTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'PRODUCT_IMAGES'").Scan(&count)
	if count > 0 {
		return
	}
	log.Println("Creating product_images table...")
	sql := `
		CREATE TABLE product_images (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			PRODUCT_ID INTEGER NOT NULL,
			URL VARCHAR2(500) NOT NULL,
			ALT_TEXT VARCHAR2(255),
			SORT_ORDER INTEGER DEFAULT 0,
			IS_PRIMARY NUMBER(1) DEFAULT 0,
			CREATED_AT TIMESTAMP WITH TIME ZONE
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating product_images table: %v", err)
		}
	} else {
		log.Println("product_images table created successfully")
	}
	db.Exec("CREATE INDEX IDX_PRODUCT_IMAGES_PRODUCT_ID ON product_images(PRODUCT_ID)")
	db.Exec("CREATE INDEX IDX_PRODUCT_IMAGES_SORT_ORDER ON product_images(SORT_ORDER)")
}

func createCartItemsTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'CART_ITEMS'").Scan(&count)
	if count > 0 {
		return
	}
	log.Println("Creating cart_items table...")
	sql := `
		CREATE TABLE cart_items (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			USER_ID INTEGER NOT NULL,
			PRODUCT_ID INTEGER NOT NULL,
			QUANTITY INTEGER DEFAULT 1,
			CREATED_AT TIMESTAMP WITH TIME ZONE,
			UPDATED_AT TIMESTAMP WITH TIME ZONE
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating cart_items table: %v", err)
		}
	} else {
		log.Println("cart_items table created successfully")
	}
	db.Exec("CREATE INDEX IDX_CART_ITEMS_USER_ID ON cart_items(USER_ID)")
	db.Exec("CREATE INDEX IDX_CART_ITEMS_PRODUCT_ID ON cart_items(PRODUCT_ID)")
}

func createWishlistItemsTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'WISHLIST_ITEMS'").Scan(&count)
	if count > 0 {
		return
	}
	log.Println("Creating wishlist_items table...")
	sql := `
		CREATE TABLE wishlist_items (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			USER_ID INTEGER NOT NULL,
			PRODUCT_ID INTEGER NOT NULL,
			CREATED_AT TIMESTAMP WITH TIME ZONE
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating wishlist_items table: %v", err)
		}
	} else {
		log.Println("wishlist_items table created successfully")
	}
	db.Exec("CREATE INDEX IDX_WISHLIST_ITEMS_USER_ID ON wishlist_items(USER_ID)")
	db.Exec("CREATE INDEX IDX_WISHLIST_ITEMS_PRODUCT_ID ON wishlist_items(PRODUCT_ID)")
}

func createOrdersTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'ORDERS'").Scan(&count)
	if count > 0 {
		return
	}

	log.Println("Creating orders table...")
	sql := `
		CREATE TABLE orders (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			USER_ID INTEGER NOT NULL,
			ORDER_CODE VARCHAR2(50) NOT NULL,
			SUBTOTAL NUMBER(15,2) NOT NULL,
			SHIPPING_FEE NUMBER(15,2) DEFAULT 0,
			DISCOUNT NUMBER(15,2) DEFAULT 0,
			TOTAL NUMBER(15,2) NOT NULL,
			STATUS VARCHAR2(50) DEFAULT 'pending',
			PAYMENT_METHOD VARCHAR2(20) DEFAULT 'cod',
			PAYMENT_STATUS VARCHAR2(20) DEFAULT 'pending',
			SHIPPING_ADDRESS VARCHAR2(500),
			NOTE VARCHAR2(500),
			CREATED_AT TIMESTAMP WITH TIME ZONE,
			UPDATED_AT TIMESTAMP WITH TIME ZONE,
			CONSTRAINT UQ_ORDERS_ORDER_CODE UNIQUE (ORDER_CODE),
			CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) REFERENCES users(ID)
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating orders table: %v", err)
		}
	} else {
		log.Println("orders table created successfully")
	}

	db.Exec("CREATE INDEX IDX_ORDERS_USER_ID ON orders(USER_ID)")
	db.Exec("CREATE INDEX IDX_ORDERS_STATUS ON orders(STATUS)")
	db.Exec("CREATE INDEX IDX_ORDERS_CREATED_AT ON orders(CREATED_AT)")
}

// ensureOrderExtraColumns makes sure new columns added later in the lifecycle
// exist even if the orders table was created before these fields were added
// to the GORM model.
func ensureOrderExtraColumns(db *gorm.DB) {
	// SHIPPING_ADDRESS_ID
	var colCount int64
	db.Raw("SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ORDERS' AND COLUMN_NAME = 'SHIPPING_ADDRESS_ID'").Scan(&colCount)
	if colCount == 0 {
		log.Println("Adding SHIPPING_ADDRESS_ID column to orders table...")
		if err := db.Exec("ALTER TABLE orders ADD SHIPPING_ADDRESS_ID INTEGER").Error; err != nil &&
			!strings.Contains(err.Error(), "ORA-01430") {
			log.Printf("Error adding SHIPPING_ADDRESS_ID column: %v", err)
		}
	}

	// SHIPPING_METHOD_CODE
	colCount = 0
	db.Raw("SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ORDERS' AND COLUMN_NAME = 'SHIPPING_METHOD_CODE'").Scan(&colCount)
	if colCount == 0 {
		log.Println("Adding SHIPPING_METHOD_CODE column to orders table...")
		if err := db.Exec("ALTER TABLE orders ADD SHIPPING_METHOD_CODE VARCHAR2(50)").Error; err != nil &&
			!strings.Contains(err.Error(), "ORA-01430") {
			log.Printf("Error adding SHIPPING_METHOD_CODE column: %v", err)
		}
	}
}

// ensureUserLoyaltyColumns guarantees loyalty_tier and loyalty_points
// exist on the users table for the loyalty feature.
func ensureUserLoyaltyColumns(db *gorm.DB) {
	var colCount int64

	// LOYALTY_TIER
	db.Raw("SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'LOYALTY_TIER'").Scan(&colCount)
	if colCount == 0 {
		log.Println("Adding LOYALTY_TIER column to users table...")
		if err := db.Exec("ALTER TABLE users ADD LOYALTY_TIER VARCHAR2(20) DEFAULT 'Bronze'").Error; err != nil &&
			!strings.Contains(err.Error(), "ORA-01430") {
			log.Printf("Error adding LOYALTY_TIER column: %v", err)
		}
	}

	// LOYALTY_POINTS
	colCount = 0
	db.Raw("SELECT COUNT(*) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'USERS' AND COLUMN_NAME = 'LOYALTY_POINTS'").Scan(&colCount)
	if colCount == 0 {
		log.Println("Adding LOYALTY_POINTS column to users table...")
		if err := db.Exec("ALTER TABLE users ADD LOYALTY_POINTS NUMBER(10) DEFAULT 0").Error; err != nil &&
			!strings.Contains(err.Error(), "ORA-01430") {
			log.Printf("Error adding LOYALTY_POINTS column: %v", err)
		}
	}
}

func createOrderItemsTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'ORDER_ITEMS'").Scan(&count)
	if count > 0 {
		return
	}

	log.Println("Creating order_items table...")
	sql := `
		CREATE TABLE order_items (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			ORDER_ID INTEGER NOT NULL,
			PRODUCT_ID INTEGER NOT NULL,
			QUANTITY INTEGER NOT NULL,
			UNIT_PRICE NUMBER(15,2) NOT NULL,
			TOTAL_PRICE NUMBER(15,2) NOT NULL,
			CONSTRAINT FK_ORDER_ITEMS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES orders(ID),
			CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID)
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating order_items table: %v", err)
		}
	} else {
		log.Println("order_items table created successfully")
	}

	db.Exec("CREATE INDEX IDX_ORDER_ITEMS_ORDER_ID ON order_items(ORDER_ID)")
	db.Exec("CREATE INDEX IDX_ORDER_ITEMS_PRODUCT_ID ON order_items(PRODUCT_ID)")
}

func createReviewImagesTable(db *gorm.DB) {
	var count int64
	db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'REVIEW_IMAGES'").Scan(&count)
	if count > 0 {
		return
	}
	log.Println("Creating review_images table...")
	sql := `
		CREATE TABLE review_images (
			ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			REVIEW_ID INTEGER NOT NULL,
			URL VARCHAR2(500) NOT NULL,
			SORT_ORDER INTEGER DEFAULT 0,
			CREATED_AT TIMESTAMP WITH TIME ZONE,
			CONSTRAINT FK_REVIEW_IMAGES_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES reviews(ID) ON DELETE CASCADE
		)
	`
	if err := db.Exec(sql).Error; err != nil {
		if !strings.Contains(err.Error(), "ORA-00955") {
			log.Printf("Error creating review_images table: %v", err)
		}
	} else {
		log.Println("review_images table created successfully")
	}
	db.Exec("CREATE INDEX IDX_REVIEW_IMAGES_REVIEW_ID ON review_images(REVIEW_ID)")
}

