apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: florus-production
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/gia-baonguyen/florus-update.git
    targetRevision: main
    path: k8s/overlays/production

  destination:
    server: https://kubernetes.default.svc
    namespace: florus-production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
