apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: florus

resources:
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: florus
  tier: application

images:
  - name: florus-backend
    newName: florus-backend
    newTag: local
  - name: florus-frontend
    newName: florus-frontend
    newTag: local
