apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: florus

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/part-of: florus
  app.kubernetes.io/managed-by: kustomize
